---
name: CI
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/build-and-test@v1
        with:
          toolchain: "1.76.0"

      - name: Compile CLI
        run: cargo build --verbose --bin yakshop_cli

      - name: Compile Web
        run: cargo build --verbose --bin yakshop_web --features="web"

      - name: Compile tests
        run: cargo test --workspace --no-run

      - name: Test
        run: cargo test --workspace

  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/lint-and-format@v1
        with:
          toolchain: "1.76.0"

      - name: Check formatting
        run: cargo +nightly fmt --check

      - name: Lint with Clippy
        run: cargo clippy --workspace --all-features --all-targets

      - name: Check locked Cargo.lock
        run: cargo check --locked --workspace --all-targets --profile=test
